'use client'
import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white font-sans">
      {/* Nav */}
      <nav className="border-b border-slate-100 bg-white">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="w-7 h-7 bg-amber-400 rounded-lg flex items-center justify-center">
              <svg className="w-3.5 h-3.5 text-slate-900" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 21h16.5M4.5 3h15M5.25 3v18m13.5-18v18M9 6.75h1.5m-1.5 3h1.5m-1.5 3h1.5m3-6H15m-1.5 3H15m-1.5 3H15M9 21v-3.375c0-.621.504-1.125 1.125-1.125h3.75c.621 0 1.125.504 1.125 1.125V21" />
              </svg>
            </div>
            <span className="text-slate-900 font-bold">ReconcileBook</span>
          </Link>
          <Link href="/" className="text-sm text-slate-500 hover:text-slate-900 transition-colors">← Back to home</Link>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-extrabold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: March 2026</p>

        <div className="prose prose-slate max-w-none space-y-8 text-slate-600 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
            <p>By creating an account or using ReconcileBook ("Service"), you agree to these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">2. Description of Service</h2>
            <p>ReconcileBook is a SaaS platform that connects to QuickBooks Online via the official Intuit API to generate job costing reports and WIP (Work in Progress) schedules for construction bookkeepers and accountants.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">3. Subscription and Billing</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>ReconcileBook is offered at <strong>$99/month</strong> per account.</li>
              <li>Billing is processed securely through Stripe.</li>
              <li>Subscriptions automatically renew each month until cancelled.</li>
              <li>You may cancel at any time from your billing portal. Access continues until the end of the current billing period.</li>
              <li>We do not offer refunds for partial months.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">4. QuickBooks Integration</h2>
            <p>ReconcileBook connects to QuickBooks Online using OAuth 2.0 authorization. By connecting a QuickBooks account, you authorize ReconcileBook to read your QuickBooks data for the purpose of generating reports. We do not modify, delete, or write data to your QuickBooks account.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Use the Service for any unlawful purpose</li>
              <li>Share your account credentials with others</li>
              <li>Attempt to reverse engineer or copy the Service</li>
              <li>Use the Service to process data you do not have authorization to access</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">6. Accuracy of Reports</h2>
            <p>ReconcileBook generates reports based on data pulled from QuickBooks Online. The accuracy of reports depends on the accuracy of data entered in QuickBooks. ReconcileBook is not responsible for errors in reports caused by incorrect or incomplete data in your QuickBooks account. Reports generated by ReconcileBook should be reviewed by a qualified accountant before use in financial decisions.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">7. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, ReconcileBook shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability for any claim shall not exceed the amount you paid us in the 3 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">8. Service Availability</h2>
            <p>We aim to maintain high availability but do not guarantee uninterrupted access. We may perform maintenance or updates that temporarily affect availability. We are not liable for downtime caused by third-party services (Intuit, Stripe, Vercel, Supabase).</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">9. Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these Terms. You may cancel your account at any time. Upon termination, your data will be deleted within 30 days.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">10. Changes to Terms</h2>
            <p>We may update these Terms from time to time. We will notify you of material changes by email. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-3">11. Contact</h2>
            <p>Questions about these Terms? Email us at <a href="mailto:alex@reconcilebookapp.com" className="text-amber-600 hover:underline">alex@reconcilebookapp.com</a>.</p>
          </section>

        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-slate-100 py-8 mt-8">
        <div className="max-w-3xl mx-auto px-6 flex items-center justify-between text-sm text-slate-400">
          <span>© {new Date().getFullYear()} ReconcileBook</span>
          <div className="flex gap-6">
            <Link href="/privacy" className="hover:text-slate-600 transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-slate-600 transition-colors">Terms</Link>
            <a href="mailto:alex@reconcilebookapp.com" className="hover:text-slate-600 transition-colors">Contact</a>
          </div>
        </div>
      </footer>
    </div>
  )
}
